blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'), #/
    url(r'^(?P<post_id>\d+)/$', views.post, name='post'), #/<postId>
    url(r'^(?P<post_id>\d+)/comment$', views.commentindex, name='commentindex'), #/<postId>/comment
    url(r'^(?P<post_id>\d+)/comment/(?P<comment_id>\d+)$', views.comment, name='comment'), #/<postId>/comment/<commentId>
    url(r'^cv$', views.cvindex, name='cvindex'), #/cv
    url(r'^contact$', views.contactindex, name='contactindex') #/contact
)

pportal/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Admin docs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin app
    url(r'^admin/', include(admin.site.urls)),

    # Blog app
    url(r'^', include('blog.urls', namespace="blog")),
)

blog/models.py
import datetime

from django.utils import timezone
from django.db import models

# Post
class Post(models.Model):
    title = models.CharField(max_length=300)
    author = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    body = models.CharField(max_length=5000)
    publish_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.body

    def published_recently(self):
        return self.publish_date <= timezone.now() and self.publish_date >= timezone.now() - datetime.timedelta(days=1)

# Comment
class Comment(models.Model):
    post = models.ForeignKey(Post)
    title = models.CharField(max_length=300)
    author = models.CharField(max_length=100)
    body = models.CharField(max_length=1000)
    publish_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.body

# Message
class Message(models.Model):
    name = models.CharField(max_length=300)
    title = models.CharField(max_length=300)
    email = models.CharField(max_length=100)
    message = models.CharField(max_length=5000)
    publish_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.message

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError
from django.core.urlresolvers import reverse

from datetime import datetime
from blog.models import Post, Comment, Message

# post list
def index(request):
    latest_post_list = __get_posts()
    return render(request, 'post/index.html', {'latest_post_list': latest_post_list})

# individual blog post
def post(request, post_id):
    post = __get_post(post_id)
    comments = __get_comments(post)
    return render(request, 'post/post.html', {'post': post, 'latest_comment_list': comments})

# comment list
def commentindex(request, post_id):

    def do_get(post, comments):
        return render(request, 'comment/index.html', {'post': post, 'latest_comment_list': comments})

    def do_post(post, comments, postData):
        comment_title = postData['commenttitle']
        comment_author = postData['commentauthor']
        comment_text = postData['commenttext']

        if comment_text:
            comment = Comment(post=post, title=comment_title, author=comment_author, body=comment_text, publish_date=datetime.now())
            comment.save()

            return HttpResponseRedirect(reverse('blog:comment', args=(post.id,comment.id)) + '#comment_' + str(comment.id))
        else:
            return do_error("Comment body must be specified")

    def do_error(error):
        return render(request, 'comment/index.html', {'post': post, 'latest_comment_list': comments, 'error_message': error})

    try:
        post = __get_post(post_id)
        comments = __get_comments(post)

        if request.POST:
            return do_post(post, comments, request.POST)
        else:
            return do_get(post, comments)

    except (MultiValueDictKeyError):
        return do_error("Comment body must be specified")

# individual comment (always viewed in post context)
def comment(request, post_id, comment_id):
    post = __get_post(post_id)
    comment = __get_comment(comment_id)
    latest_comment_list = __get_comments(post)
    return render(request, 'comment/comment.html', {'post': post, 'comment': comment, 'latest_comment_list': latest_comment_list})

# cv
def cvindex(request):
    return render(request, 'cv/index.html')

# contact
def contactindex(request):
    try:
        if request.method == 'POST':
            if request.POST['subject'] and request.POST['name'] and request.POST['email'] and request.POST['message']:
                message = Message(title=request.POST['subject'], name=request.POST['name'], email=request.POST['email'], message=request.POST['message'], publish_date=datetime.now())
                message.save()
                return render(request, 'contact/index.html', {'success_message': 'Your message has been delivered'})
            else:
                return render(request, 'contact/index.html', {'error_message': 'Could not send message. Make sure that you have provided all info.'})
        else:
            return render(request, 'contact/index.html')

    except MultiValueDictKeyError as e:
        return render(request, 'contact/index.html', {'error_message': 'Could not send message. Make sure that you have provided all info.'})

#TODO abstract away form view. model would be a good place?
def __get_post(post_id):
    return get_object_or_404(Post, pk=post_id)

def __get_posts():
    return Post.objects.order_by('-publish_date')[:5]

def __get_comment(comment_id):
    return get_object_or_404(Comment, pk=comment_id)

def __get_comments(post):
    return Comment.objects.filter(post_id=post.id).order_by('-publish_date')[:5]

blog/templates/comment/comment.html
{% extends "post/post.html" %}

{% block comments %}
<h4>Comments:</h4>
    {% if latest_comment_list %}
        {% for listcomment in latest_comment_list %}
            {% if comment.id == listcomment.id %}
            <div class="well highlight" id="comment_{{ listcomment.id }}">
                <span class="label label-success">  Currently viewing</span>
            {% else %}
                <div class="well" id="comment_{{ listcomment.id }}">
            {% endif %}
            <h5>{{ listcomment.title }} - [ {{listcomment.author}} ]</h5>
            <p>{{ listcomment.body }}</p>
        </div>
        {% endfor %}
    {% else %}
        No comments
    {% endif %}
{% endblock %}

blog/templates/comment/index.html
{% extends "post/post.html" %}

blog/templates/contact/index.html
{% extends "front/layout.html" %}
{% block navcontact %}active{% endblock %}

{% block content %}
<div class="row">
    <div class="span10 offset1">
        <form method="post" action="{% url 'blog:contactindex' %}" class="form-horizontal well">
            {% csrf_token %}
            <fieldset>
                <legend>
                    Contact me
                </legend>
                {% if success_message %}
                <div class="alert alert-success">
                    {{ success_message }}
                </div>
                {% endif %}

                {% if error_message %}
                <div class="alert alert-error">
                    {{ error_message }}
                </div>
                {% endif %}
                <div class="control-group">
                    <label class="control-label" for="subject">Subject:</label>
                    <div class="controls">
                        <input type="text" class="input-xlarge" id="subject" name="subject">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="name">Name:</label>
                    <div class="controls">
                        <input type="text" class="input-xlarge" id="name" name="name">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="email">E-mail:</label>
                    <div class="controls">
                        <input type="text" class="input-xlarge" id="email" name="email">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="message">Message:</label>
                    <div class="controls">
                        <textarea class="input-xlarge" id="message" rows="4" name="message"></textarea>
                    </div>
                </div>

                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">Send</button>
                    <button type="reset" class="btn">Cancel</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/cv/index.html
{% extends "front/layout.html" %}
{% block navcv %}active{% endblock %}
{% block content %}
    <div class="page-header">
        <h1>CV</h1>
    </div>

    <div class="span5">
        <h3>Areas of expertise:</h3>
            <ul>
                <li>Linux</li>
                <li>Apache</li>
                <li>MySQL</li>
                <li>PHP 5.3+ / Zend Certified</li>
                <li>Varnish Cache</li>
                <li>Webservices</li>
                <li>HTML</li>
                <li>JavaScript</li>
                <li>NodeJS</li>

                <li>Java</li>
                <li>Polopoly CMS</li>
                <li>Android SDK</li>
            </ul>

            <h3>Currently learning/playing with</h3>
            <ul>
                <li>Python</li>
                <li>Django</li>
            </ul>
        <h3>Work experience:</h3>
        <ul>
            <li>Developer, VG Mobil AS 2011-2013</li>
            <li>Senior Developer, Edda Media AS (2010 - 2011)</li>

            <li>Developer, Edda Media AS (2007-2010)</li>

        </ul>
        <h3>Reading:</h3>
        <ul>
            <li>Hackernews</li>
        </ul>
        <h3>Education:</h3>
            BSc Computer Science (Honours) - University of Leicester (2004-2007)

    </div>

    <div class="span5">
        <h3>Preferred environment:</h3>
        <a href="{{ STATIC_URL }}img/andreas/workshot.png"><img src="{{ STATIC_URL }}img/andreas/workshot-thumb.png"></a>
        <h4>Workspace:</h4>
        <ul>
            <li>Linux x86_64 (Arch Linux)</li>
            <li>AwesomeWM</li>
            <li>urxvt (Unicode, 256 colour)</li>
            <li>vim + ctrlP,nerdTree,YouCompleteMe</li>
        </ul>

        <h3>Social</h3>
        <div>
            <a class="btn btn-info btn-large" href="http://www.github.com/andreasrs">Github</a>
            <a class="btn btn-info btn-large" href="http://www.linkedin.com/pub/andreas-rudi-s%C3%B8vik/10/bb0/562">LinkedIn</a>
        </div>
    </div>
{% endblock %}

blog/templates/post/index.html
{% extends "front/layout.html" %}
{% block navblog %}active{% endblock %}
{% block content %}
    {% if latest_post_list %}
        {% for post in latest_post_list %}
            <div class="span4">
                <h2>{{ post.title }}</h2>
                <p>{{ post.description }}</p>
                <p><a class="btn" href="{% url 'blog:post' post.id %}">Read more &raquo;</a></p>
            </div>
        {% endfor %}
    {% else %}
        <div class="span1">
            <h2>No posts</h2>
        </div>
    {% endif %}
{% endblock %}

{% block extracontent %}
    <div class="jumbotron">
        <h1>Get in touch!</h1>
        <p class="lead">I can help with system design and implementation</p>
        <a class="btn btn-large btn-success" href="http://www.linkedin.com/pub/andreas-rudi-s%C3%B8vik/10/bb0/562">Go to my LinkedIn</a>
    </div>

    <hr>

    <div>
        <h3>Latest tweets (@arsovik)</h3>
        <div id="tweetbox"></div>
    </div>

    <script>
        requirejs(['jquery', 'bootstrap', 'js/tweetbox'], function($, _bootstrap, tweetbox) {
            //tweetbox.attach('#tweetbox');
        });
    </script>
{% endblock %}

blog/templates/post/post.html
{% extends "front/layout.html" %}
{% block navblog %}active{% endblock %}
{% block content %}
    <div class="well">
        <h1>{{ post.title }}</h1>
        <h3>{{ post.description }}</h3>
        <p>{{ post.body }}</p>
    </div>

    <div>
        {% block comments %}
            <h4>Comments:</h4>
            {% if latest_comment_list %}
                {% for comment in latest_comment_list %}
                <div class="well" id="comment_{{ comment.id }}">
                    <h5>{{ comment.title }} - [ {{comment.author}} ]</h5>
                    <p>{{ comment.body }}</p>
                </div>
                {% endfor %}
            {% else %}
                No comments
            {% endif %}
        {% endblock %}
    </div>

    <div class="well" id="post">
        <h4>Make a comment</h4>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'blog:commentindex' post.id %}#post" method="post">
            {% csrf_token %}
            <div><label for="commenttitle">Title</label><input type="text" class="input-xlarge" name="commenttitle"></input></div>
            <div><label for="commentauthor">Author</label><input type="text" class="input-xlarge" name="commentauthor"></input></div>
            <label for="commenttext">Comment</label><textarea class="input-xlarge" rows="4" name="commenttext" id="commenttext"></textarea>
            <div>
                <input class="btn btn-large" type="submit" value="Post" />
            </div>
        </form>
    </div>
{% endblock %}

pportal/templates/front/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Portal: Andreas Søvik | andreasrs.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="A personal blogging portal">
        <meta name="author" content="Andreas Rudi Søvik">

        <script src="{{ STATIC_URL }}vendor/requirejs/js/require.js"></script>

        <link href="{{ STATIC_URL }}vendor/bootstrap/css/slate/bootstrap.min.css" rel="stylesheet">
        <link href="{{ STATIC_URL }}vendor/bootstrap/css/market/market.css" rel="stylesheet">
        <link href="{{ STATIC_URL }}css/pportal.css" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="../assets/js/html5shiv.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="container">

            <div class="masthead">
                <h2 class="muted">Andreas Søvik</h2>
                <div class="navbar">
                    {% block navigation %}
                    <div class="navbar-inner">
                        <div class="container">
                            <ul class="nav">
                                <li class="{% block navblog %}{% endblock %}"><a href="{% url 'blog:index' %}">Blog</a></li>
                                <li class="{% block navcv %}{% endblock %}"><a href="/cv">CV</a></li>
                                <li class="{% block navcontact %}{% endblock %}"><a href="/contact">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    {% endblock %}
                </div><!-- /.navbar -->
            </div>

            <div class="row-fluid">
                {% block content %}{% endblock %}
            </div>

            <hr>

            {% block extracontent %}{% endblock %}


            <div class="footer mid">
                <strong><p>&copy; Andreas Rudi Søvik 2013</p></strong>
            </div>

            <div class="row mid">
                Powered by: Python | Django | MySQL | Bootstrap
            </div>

        </div> <!-- /container -->

        <script>
            (function() {
                requirejs.config({
                    baseUrl: '/static',
                    paths: {
                        jquery: 'vendor/jquery/jquery-1.10.2.min',
                        bootstrap: 'vendor/bootstrap/js/bootstrap.min'},
                    shim: {
                        'bootstrap':{deps: ['jquery']}
                    }
                });

                requirejs(['jquery', 'bootstrap', 'js/pportal'], function($, _bootstrap, pportal) {
                    pportal.start();
                });
            })();
        </script>
    </body>
</html>